language: node_js
node_js:
  - lts/*

install:
  - yarn install # npm ci

script:
  - yarn build # npm run docs:build
  - cd docs/.vuepress/dist
  - touch .nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master